services:
  - type: web
    name: cloud-notes-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app4:app
    envVars:
      - key: PORT
        value: 10000
